version: "3.8"

services:
  db:
    image: postgres:16.0-alpine3.17
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5433:5432"
    volumes:
      - my_db:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U tea_atlas_user -d tea_atlas_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: ./backend
    container_name: backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
#      - my_media:/files/media
      - my_media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "5173:80"
    depends_on:
      - web
    restart: always

volumes:
  my_db:
  my_media:
