# Generated by Django 5.1.6 on 2025-02-27 18:59

import django.db.models.deletion
import tea_catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=68, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Description",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=63, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Descriptor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=63, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "province",
                    models.CharField(blank=True, max_length=68, null=True, unique=True),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=tea_catalog.models.tea_image_file_path,
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tea_catalog.country",
                    ),
                ),
            ],
            options={
                "ordering": ["country"],
                "unique_together": {("country", "province")},
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "fermentation",
                    models.CharField(
                        choices=[
                            ("Minimally Oxidized", "Mn"),
                            ("Lightly Oxidized", "Lt"),
                            ("Moderately Oxidized", "Md"),
                            ("Heavily Oxidized", "Hv"),
                            ("Fully Oxidized", "Fl"),
                            ("Post-Fermented", "Pf"),
                        ],
                        default="Minimally Oxidized",
                        max_length=19,
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tea_catalog.region",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "effect",
                    models.CharField(
                        choices=[
                            ("Warming", "Wm"),
                            ("Cooling", "Co"),
                            ("Balancing", "Bl"),
                            ("Moisturizing", "Mo"),
                            ("Cleansing", "Cl"),
                            ("Aids digestion", "Ad"),
                        ],
                        default="Balancing",
                        max_length=14,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=tea_catalog.models.tea_image_file_path,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tea_catalog.category",
                    ),
                ),
                (
                    "descriptors",
                    models.ManyToManyField(
                        related_name="tea", to="tea_catalog.descriptor"
                    ),
                ),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
    ]
