# Generated by Django 5.1.6 on 2025-02-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tea_catalog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tea",
            name="effect",
        ),
        migrations.AddField(
            model_name="tea",
            name="impact",
            field=models.CharField(
                choices=[
                    ("Warming", "Wm"),
                    ("Cooling", "Co"),
                    ("Balancing", "Bl"),
                    ("Moisturizing", "Mo"),
                    ("Cleansing", "Cl"),
                    ("Aids digestion", "Ad"),
                ],
                default="Balancing",
                max_length=14,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="fermentation",
            field=models.CharField(
                choices=[
                    ("Minimally Oxidized", "Mn"),
                    ("Lightly Oxidized", "Lt"),
                    ("Moderately Oxidized", "Md"),
                    ("Heavily Oxidized", "Hv"),
                    ("Fully Oxidized", "Fl"),
                    ("Post-Fermented", "Pf"),
                ],
                default="Minimally Oxidized",
                max_length=19,
            ),
        ),
    ]
