# Generated by Django 5.1.6 on 2025-03-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tea_catalog", "0002_alter_category_fermentation_alter_tea_impact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="fermentation",
            field=models.CharField(
                choices=[
                    ("Minimally Oxidized", "Minimally"),
                    ("Lightly Oxidized", "Lightly"),
                    ("Moderately Oxidized", "Moderately"),
                    ("Heavily Oxidized", "Heavy"),
                    ("Fully Oxidized", "Fully"),
                    ("Post-Fermented", "Post Fermented"),
                ],
                default="Minimally Oxidized",
                max_length=19,
            ),
        ),
        migrations.AlterField(
            model_name="tea",
            name="impact",
            field=models.CharField(
                choices=[
                    ("Warming", "Warming"),
                    ("Cooling", "Cooling"),
                    ("Balancing", "Balancing"),
                    ("Moisturizing", "Moisturizing"),
                    ("Cleansing", "Cleansing"),
                    ("Aids digestion", "Aids Digestion"),
                ],
                default="Balancing",
                max_length=14,
            ),
        ),
    ]
