# Generated by Django 5.1.6 on 2025-03-26 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tea_catalog", "0003_alter_category_fermentation_alter_tea_impact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="fermentation",
            field=models.CharField(
                choices=[
                    ("Minimally Oxidized", "Minimally"),
                    ("Lightly Oxidized", "Lightly"),
                    ("Moderately Oxidized", "Moderately"),
                    ("Heavily Oxidized", "Heavy"),
                    ("Fully Oxidized", "Fully"),
                    ("Post-Fermented", "Post Fermented"),
                ],
                default="Minimally Oxidized",
                max_length=19,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="tea",
            name="impact",
            field=models.CharField(
                choices=[
                    ("Warming", "Warming"),
                    ("Cooling", "Cooling"),
                    ("Balancing", "Balancing"),
                    ("Moisturizing", "Moisturizing"),
                    ("Cleansing", "Cleansing"),
                    ("Aids digestion", "Aids Digestion"),
                ],
                default="Balancing",
                max_length=14,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("name", "region")},
        ),
        migrations.CreateModel(
            name="Steeping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("leaves", models.IntegerField()),
                ("water_volume", models.IntegerField()),
                ("water_temperature", models.IntegerField()),
                ("steep_time", models.IntegerField()),
                ("infusion", models.IntegerField()),
                (
                    "tea_category",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tea_catalog.category",
                    ),
                ),
            ],
            options={
                "ordering": ["tea_category"],
            },
        ),
    ]
